#version: '3'
#
#services:
#  kotlin-final-app:
#    image: kotlin-final-app
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - shop
#    ports:
#      - 8080:8080
#    expose:
#      - '8080'
#    volumes:
#      - /data/kotlin-final-app

version: '3.3'
services:
  kotlin-final-app:
    image: kotlin-final-app
    restart: always
    ports:
      - 8080:8080
    expose:
      - '8080'
